### PR TITLE
Removed statuspage and fastly fingerprints.

### PR DESCRIPTION
**Pull request by sumgr0**
These are no longer vulnerable to takeovers

### CODE REVIEW

**Comment by shmilylty** [comment]
Are you sure that these two domain names no longer have the risk of subdomain takeover? Have you done any confirmation work, currently I am in
The [can-i-take-over-xyz](https://github.com/EdOverflow/can-i-take-over-xyz) project saw that these two fingerprints are still valid. @sumgr0

**Comment by sumgr0** [comment]
statuspage is no longer after user piral261 reported them the bug: https://github.com/EdOverflow/can-i-take-over-xyz/pull/105

fastly i'll have to check the source again...

**Comment by shmilylty** [comment]
> statuspage is no longer after user piral261 reported them the bug: [EdOverflow/can-i-take-over-xyz#105](https://github.com/EdOverflow/can-i-take-over-xyz/pull/105)
> 
> fastly i'll have to check the source again...

Ok, I look forward to your reply. If you find a new fingerprint from its other projects, you are welcome to submit it ~

**Comment by shmilylty** [comment]
how is the progress? @sumgr0

**Comment by sumgr0** [comment]
I'm not able to recall the exact post/reference for fastly, accept for personal experience.

Have you come across any vulnerable subdomain pointing to fastly?

**Comment by shmilylty** [comment]
Unverified, temporarily closed.

**Pull request closed without merging**
